version: '3.3'
# see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamo-data-volume/data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
#  app-node:
#    depends_on:
#      - dynamodb-local
#    image: banst/awscli
#    container_name: app-node
#    ports:
#     - "8080:8080"
#    environment:
#      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
#      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
#    command:
#      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region us-east-2
#volumes:
#  data-volume:
